spring:
  application:
    name: exemplo redis
    datasource:
    hikari:
      minimum-idle: 1
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
